# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IdeaTrying' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IdeaTrying
  pod 'Alamofire'
  pod 'SnapKit'

  target 'IdeaTryingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IdeaTryingUITests' do
    # Pods for testing
  end

end
